In [ ]:
import re
import numpy as np
import matplotlib as mat
import matplotlib.pyplot as plt
                    # to visualize 
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import json
from time import time
import re
import spacy
from spacy.lang.en import English
import collections
from collections import Counter
import nltk
en = spacy.load("en_core_web_sm")                          
Stop_words=en.Defaults.stop_words
en.max_length=155507299 
import nltk
nltk.download('punkt')
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
df_r=pd.read_csv("/content/drive/MyDrive/Project/file2.csv")

In [ ]:
df_r.isnull().sum()

Unnamed: 0         0
overall            0
reviewTime         0
reviewerID         0
asin               0
reviewerName     336
reviewText      3776
dtype: int64

In [ ]:
df_r.dropna(inplace=True)

In [ ]:
df_r=df_r.drop('Unnamed: 0',axis=1)

In [ ]:
def cleaning(text):
   
    text = re.sub("[^0-9A-Za-z\- ]+", " ", text)  # Remove all non-letters and non-spaces except for hyphens and digits
    
    text = re.sub("(?<!\w)\d+", "", text)  # Remove all numbers except those attached to a word
    
    text = re.sub("-(?!\w)|(?<!\w)-", "", text)  # Remove all hyphens except between two words
    
    text = " ".join(text.split()) # Remove multiple spaces and lowercase everything
    
    text = text.lower() #convert all words to lower case
    
    
    return text

In [ ]:
df_r

,overall,reviewTime,reviewerID,asin,reviewerName,reviewText
0,2.0,"09 22, 2016",A1IDMI31WEANAF,0020232233,Mackenzie Kent,when it comes to a dm s screen the space on th...
1,1.0,"09 18, 2016",A4BCEVVZ4Y3V3,0020232233,Jonathan Christian,an open letter to galeforce9 your unpainted mi...
2,3.0,"09 12, 2016",A2EZ9PY1IHHBX0,0020232233,unpreparedtodie,nice art nice printing why two panels are fill...
3,5.0,"03 2, 2017",A139PXTTC2LGHZ,0020232233,Ashley,amazing buy bought it as a gift for our new dm...
4,1.0,"02 8, 2017",A3IB33V29XIL8O,0020232233,Oghma_EM,as my review of gf9 s previous screens these w...
...,...,...,...,...,...,...
8193610,5.0,"12 7, 2017",A3OCDEVI6FGUWU,B01HJBAKIO,wilson,my son is happy
8193611,5.0,"01 23, 2016",A1KTVUVADLKWZO,B01HJHA7GI,Raven the Maven,e my ten month old has had this for a few mont...
8193612,5.0,"02 8, 2015",A2QCA9OE62IPZ4,B01HJHA7GI,crhug,perfect toy to keep baby amused
8193613,5.0,"12 31, 2014",A3N28JAZYS4L9O,B01HJHA7GI,Cindy Volk,perfect
8193614,5.0,"11 11, 2014",A2OGYZRYRSVQZJ,B01HJHA7GI,Ostinato_Parody,i am based in the uk and i bought this item as...

In [ ]:
df_meta=pd.read_csv("/content/drive/MyDrive/Project/file1.csv")

In [ ]:
df_meta.isnull().sum()

Unnamed: 0        0
category          0
description       0
title            21
brand          6927
main_cat       4694
asin              0
dtype: int64

In [ ]:
df_meta.dropna(inplace=True)

In [ ]:
df_meta.columns

Index(['Unnamed: 0', 'category', 'description', 'title', 'brand', 'main_cat',
       'asin'],
      dtype='object')

In [ ]:
col=[ 'category', 'description', 'title', 'brand', 'main_cat']

In [ ]:
for i in col:
  df_meta[i]=df_meta[i].apply(cleaning)

In [ ]:
df_meta=df_meta.drop('Unnamed: 0',axis=1)

In [ ]:
df=pd.merge(df_r,df_meta,on='asin')

In [ ]:
stp_words=stopwords.words('english')
def clean_review(review):
  cleanreview=" ".join(word for word in review.
                       split() if word not in stp_words)
  return cleanreview
 
df['reviewText']=df['reviewText'].apply(clean_review)

In [ ]:
from textblob import TextBlob

# function to calculate polarity
def getPolarity(review):
  return TextBlob(review).sentiment.polarity

# function to analyze the reviews
def analysis(score):
    if score < 0:
        return 'Negative'
    elif score == 0:
        return 'Neutral'
    else:
        return 'Positive'

In [ ]:
df['Polarity'] = df['reviewText'].apply(getPolarity) 
df['Analysis'] = df['Polarity'].apply(analysis)
df.head()

,overall,reviewTime,reviewerID,asin,reviewerName,reviewText,category,description,title,brand,main_cat,Polarity,Analysis
0,2.0,"09 22, 2016",A1IDMI31WEANAF,0020232233,Mackenzie Kent,comes dm screen space screen absolute premium ...,toys games grown-up toys games,this screen is the perfect companion for those...,dungeons amp dragons quot storm kings thunder ...,gale force nine,toys games,-0.242857,Negative
1,1.0,"09 18, 2016",A4BCEVVZ4Y3V3,0020232233,Jonathan Christian,open letter galeforce9 unpainted miniatures ba...,toys games grown-up toys games,this screen is the perfect companion for those...,dungeons amp dragons quot storm kings thunder ...,gale force nine,toys games,-0.019468,Negative
2,3.0,"09 12, 2016",A2EZ9PY1IHHBX0,0020232233,unpreparedtodie,nice art nice printing two panels filled gener...,toys games grown-up toys games,this screen is the perfect companion for those...,dungeons amp dragons quot storm kings thunder ...,gale force nine,toys games,0.118243,Positive
3,5.0,"03 2, 2017",A139PXTTC2LGHZ,0020232233,Ashley,amazing buy bought gift new dm perfect,toys games grown-up toys games,this screen is the perfect companion for those...,dungeons amp dragons quot storm kings thunder ...,gale force nine,toys games,0.578788,Positive
4,1.0,"02 8, 2017",A3IB33V29XIL8O,0020232233,Oghma_EM,review gf9 previous screens completely unneces...,toys games grown-up toys games,this screen is the perfect companion for those...,dungeons amp dragons quot storm kings thunder ...,gale force nine,toys games,-0.316667,Negative

In [ ]:
df.Analysis.value_counts()

Positive    6747280
Negative     904967
Neutral      739837
Name: Analysis, dtype: int64

In [ ]:
df

,overall,reviewTime,reviewerID,asin,reviewerName,reviewText,category,description,title,brand,main_cat,Polarity,Analysis
0,2.0,"09 22, 2016",A1IDMI31WEANAF,0020232233,Mackenzie Kent,comes dm screen space screen absolute premium ...,toys games grown-up toys games,this screen is the perfect companion for those...,dungeons amp dragons quot storm kings thunder ...,gale force nine,toys games,-0.242857,Negative
1,1.0,"09 18, 2016",A4BCEVVZ4Y3V3,0020232233,Jonathan Christian,open letter galeforce9 unpainted miniatures ba...,toys games grown-up toys games,this screen is the perfect companion for those...,dungeons amp dragons quot storm kings thunder ...,gale force nine,toys games,-0.019468,Negative
2,3.0,"09 12, 2016",A2EZ9PY1IHHBX0,0020232233,unpreparedtodie,nice art nice printing two panels filled gener...,toys games grown-up toys games,this screen is the perfect companion for those...,dungeons amp dragons quot storm kings thunder ...,gale force nine,toys games,0.118243,Positive
3,5.0,"03 2, 2017",A139PXTTC2LGHZ,0020232233,Ashley,amazing buy bought gift new dm perfect,toys games grown-up toys games,this screen is the perfect companion for those...,dungeons amp dragons quot storm kings thunder ...,gale force nine,toys games,0.578788,Positive
4,1.0,"02 8, 2017",A3IB33V29XIL8O,0020232233,Oghma_EM,review gf9 previous screens completely unneces...,toys games grown-up toys games,this screen is the perfect companion for those...,dungeons amp dragons quot storm kings thunder ...,gale force nine,toys games,-0.316667,Negative
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8392079,5.0,"08 26, 2016",A3FFQ7G5V45WJ5,B01HJDGVFS,Amazon Customer,son months enjoyed playing pool,toys games sports outdoor play pools water fun...,suitable for children ages months old br warni...,micord baby float toddler swimming inflatable ...,micord,toys games,0.500000,Positive
8392080,5.0,"01 23, 2016",A1KTVUVADLKWZO,B01HJHA7GI,Raven the Maven,e ten month old months never tires classical s...,toys games baby toddler toys music sound,,baby einstein take along tunes musical toy,baby einstein,baby,0.031439,Positive
8392081,5.0,"02 8, 2015",A2QCA9OE62IPZ4,B01HJHA7GI,crhug,perfect toy keep baby amused,toys games baby toddler toys music sound,,baby einstein take along tunes musical toy,baby einstein,baby,1.000000,Positive
8392082,5.0,"12 31, 2014",A3N28JAZYS4L9O,B01HJHA7GI,Cindy Volk,perfect,toys games baby toddler toys music sound,,baby einstein take along tunes musical toy,baby einstein,baby,1.000000,Positive
8392083,5.0,"11 11, 2014",A2OGYZRYRSVQZJ,B01HJHA7GI,Ostinato_Parody,based uk bought item gift friend daughter reli...,toys games baby toddler toys music sound,,baby einstein take along tunes musical toy,baby einstein,baby,0.120833,Positive

In [ ]:
df=df.drop('title',axis=1)